# Generated by Django 5.2 on 2026-02-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='restaurant_name_idx')],
            },
        ),
    ]
