# Generated by Django 5.2 on 2026-03-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikedinder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
